[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "acca"
authors = [{name = "Haruto Nakayama", email = "nakayama.haruto@aist.go.jp"}]
readme = "README.md"
license = {file = "LICENSE"}
description = "Automatic-Crowd-Congestion-Analysis-System"
version = "2025.11"

dependencies = [
    "aiaccel",
    "einops",
    "hydra-core@git+https://github.com/facebookresearch/hydra.git",
    "omegaconf@git+https://github.com/omry/omegaconf.git",
    "rich",
    "matplotlib",
    "lightning",
    "kornia",
    "numpy",
    "torch",
    "soundfile",
    "librosa",
    "torchaudio",
    "torchmetrics",
    "torchvision",
    "pyyaml",
    "nvidia-dali-cuda120",
]

[project.urls]
Home = "https://ybando.jp"

[project.optional-dependencies]
dev = [
    "mpi4py",
    "h5py",
    "tensorboard",
    "tensorboard-data-server",
    "myst-parser",
    "markdown-it-py>=3.0,<4.0",
    "ruff",
    "pystoi",
    "pandas",
    "sphinx",
    "sphinxcontrib-jquery",
    "sphinx-intl",
    "sphinx-fontawesome",
    "sphinx-rtd-theme",
    "sphinx-copybutton",
    "sphinx-autobuild",
    "sphinx_design",
    "shibuya"
]

[tool.ruff]
line-length = 120
target-version = "py312"

[tool.ruff.lint]
select = ["E", "F", "UP", "B", "SIM", "I"]

[tool.ruff.lint.isort]
force-sort-within-sections = true

section-order = [
    "future",
    "typing",
    "standard-library",
    "utilities",
    "datascience",
    "torch",
    "torch-third-party",
    "third-party",
    "audio",
    "first-party",
    "local-folder"
]

[tool.ruff.lint.isort.sections]
"typing" = ["typing"]
"utilities" = ["progressbar", "omegaconf", "hydra"]
"datascience" = ["numpy", "scipy", "pandas", "matplotlib", "opt_einsum", "einops"]
"torch" = ["torch"]
"torch-third-party" = ["torchaudio", "torchvision", "auraloss", "lightning", "einops.layers"]
"audio" = ["librosa", "pypesq", "pystoi", "soundfile"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

# feature.pre-install
[tool.pixi.feature.pre-install.dependencies]
git = "*"
c-compiler = "*"
zlib = "*"
pkg-config = "*"

[tool.pixi.feature.pre-install.activation.env]
HDF5_VERSION = "1.14.6"
MPI4PY_VERSION = "4.1.1"
H5PY_VERSION = "3.14.0"
CC = "mpicc"

[tool.pixi.feature.pre-install.tasks]
build-hdf5 = """
rm -rf $PIXI_PROJECT_ROOT/3rd/hdf5 && \
mkdir -p $PIXI_PROJECT_ROOT/3rd/hdf5/_build && cd $PIXI_PROJECT_ROOT/3rd/hdf5/_build && \
wget https://github.com/HDFGroup/hdf5/releases/download/hdf5_$HDF5_VERSION/hdf5-$HDF5_VERSION.tar.gz && \
tar xf hdf5-$HDF5_VERSION.tar.gz && \
cd hdf5-$HDF5_VERSION && \
./configure \
    --prefix=$PIXI_PROJECT_ROOT/3rd/hdf5 \
    --with-zlib=$CONDA_PREFIX/lib \
    --enable-parallel \
    --enable-shared && \
make -j $(nproc) && \
make install && \
make check-install
"""

remove-cache = """
bash -c 'find $HOME/.cache/rattler -depth -name "aiaccel" -print -exec rm -r {} \\;'
bash -c 'find $HOME/.cache/rattler -depth -name "mpi4py" -print -exec rm -r {} \\;' && \
bash -c 'find $HOME/.cache/rattler -depth -name "h5py" -print -exec rm -r {} \\;'
"""

# feature.dev
[tool.pixi.feature.dev.pypi-options]
no-build-isolation = ["mpi4py", "h5py"]
no-binary = ["mpi4py", "h5py", "gpuRIR"]

[tool.pixi.feature.dev.dependencies]
tensorboard-data-server = ">=0.7.0,<0.8"
markdown-it-py = ">=3.0,<4.0"

# feature.dev-tools
[tool.pixi.feature.dev-tools.dependencies]
byobu = "*"
direnv = "*"
bat = "*"
htop = "*"
bzip2 = "*"
unzip = "*"
colordiff = "*"
wget = "*"
curl = "*"
make = ">=4.4"
cmake = "*"
pre-commit = "*"
sox = "*"
ffmpeg = ">=8.0.0"

[tool.pixi.feature.dev-tools.pypi-dependencies]
optuna = "*"
jupyter = "*"

[tool.pixi.activation.env]
PATH = "$PIXI_PROJECT_ROOT/3rd/hdf5/bin:$PATH"
LD_LIBRARY_PATH = "$PIXI_PROJECT_ROOT/3rd/hdf5/lib:$LD_LIBRARY_PATH"
HDF5_MPI = "ON"
HDF5_DIR = "$PIXI_PROJECT_ROOT/3rd/hdf5"

[tool.pixi.dependencies]
python = ">=3.12.8,<3.13"
openjdk = "*"
blas = { version = "*", build = "mkl" }
rich = "*"
numpy = "*"
scipy = "*"
cython = "*"
cuda = "12.8.*"
procps-ng = ">=4.0.4,<5"
openmpi-mpicc = "*"

[tool.pixi.pypi-dependencies]
# acca = { path = ".", editable = true }
pkgconfig = "*"
cupy-cuda12x = "*"

nvidia-dali-cuda120 = { version = "*", index = "https://pypi.nvidia.com" }
timm = "*"
sympy = "==1.12.1"
lap = "*"
opencv-python = "*"
pydantic = "*"


[tool.pixi.pypi-options]


[tool.pixi.environments]
pre-install = { features = ["pre-install"], no-default-feature = true }
default = { features = ["dev", "dev-tools", "pre-install"], solve-group = "default" }

[tool.pixi.tasks]
