[project]
name = "acca"
authors = [{name = "Haruto Nakayama", email = "nakayama.haruto@aist.go.jp"}]
readme = "README.md"
license = {file = "LICENSE"}
description = "Automatic-Crowd-Congestion-Analysis-System"
version = "2026.01"

requires-python = ">=3.12.8,<3.13"

dependencies = [
    "ruff",
    "matplotlib",
    "lightning",
    "numpy",
    "torch",
    "torchaudio",
    "torchmetrics",
    "torchvision",
    "pyyaml",
    "nvidia-dali-cuda120",
    "albumentations",
    "scipy",
    "cython",
    "timm",
    "sympy",
    "lap",
    "pydantic",
    "opencv-python",
    "hydra-core",
    "omegaconf",
    "tqdm",
]
