defaults:
  - _self_
  - tracker: bytetrack

node_type: "rt_HC"
result_dir: "demo_outputs/demo_videos/results"

hydra_log_dir: "demo_outputs/demo_videos/tracking_hydra_log"

hydra:
  run:
    dir: "${hydra_log_dir}"