defaults:
  - _self_
  - detector: p2pnet
  - detection_visualizer: display_detection
  - tracker: bytetrack
  - tracking_visualizer: display_trajectory

pipeline:
  - detector
  # - detection_visualizer
  - tracker
  # - tracking_visualizer

video_dir: "/homes/hnakayama/automatic_crowd_analysis/videos"
output_dir: "outputs"
video_extension: "MOV"

task_index: 1
task_stepsize: 1